### ISSUE TITLE
SharePoint Tab will not load (loading spinner)

### ISSUE THREAD

**Issue by diabhoil** [YannickRe/SharePoint-Page-Teams-Embed#5]
Hey,

I am building a Teams app where an team manager can pin a tab with a specific SharePoint url to the team. This was working before (at least so far I know). But since a while it stopped working and I was searching for a solution. I found the linked [blog article](https://blog.yannickreekmans.be/show-sharepoint-page-in-microsoft-teams/). Sadly the workaround over the teamslogon.aspx page is not working so far. To be clear: It is working in the web or in the desktop app when I already visited a linked SharePoint page in an different tab (for example pinned with the Website app) and logged in. But in the desktop app, when I log out (or as a "new" user) and I visit my pinned tab, I just get the loading spinner. 

When I open the Developer Tools from the Desktop Client I can reload the tab and get the following error message:
![image](https://user-images.githubusercontent.com/42711805/104043458-24622980-51dc-11eb-8b69-7e3888408141.png)

The error message is: "App webApplicationInfo or resource not defined in manifest".

The code in my config page to save the tab is:
```
let url = "https://m365xxxxxx.sharepoint.com/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/sites/ss/SitePages/Empty-Page-Somewhere-else.aspx";
let contentUrl = url;
let title = new Date().toString() + "";

microsoftTeams.settings.setSettings({
       entityId: "xxxx",
       contentUrl: contentUrl,
       suggestedDisplayName: title,
       websiteUrl: url,
       removeUrl: window.location.origin + "/remove.html?teams=1"
});
```

The relevant manifest part is:
```
    "validDomains": [
        "*.sharepoint.com",
        "msft.spoppe.com",
        "resourceseng.blob.core.windows.net",
        "spoprod-a.akamaihd.net",
        "spoppe-a.akamaihd.net",
        "*.sharepoint-df.com",
        "*.login.microsoftonline.com"
    ],
    "webApplicationInfo": {
        "resource": "https://m365xxxxxxx.sharepoint.com",
        "id": "00000003-0000-0ff1-ce00-000000000000"
    }
```

What I did so far:

- checked the url in the resource part of the manifest. No typo there
- replaced all domains in the validDomains section, pasted the correct SharePoint url there instead of the *.sharepoint.com
- tested different urls in the config part (instead of the root url in the first part used the full url to the site, in the dest part used the absolute path instead of the relative one)
- tested different pages (my target page would be one with a spfx webpart on it. So I tested with a blank page instead)
- tested different sites (team site, communication site, the team site where I pinned the tab)
- added _&inTeamsSSO=True_ to the teamslogon.aspx parameters
- changed the manifest version from 1.7 to 1.5
- retyped the webApplicationInfo part in the manifest to exclude a copy and paste error
- tested different users (admin account, account with just read rights to the specific sites)
- tested with Teams on my working machine and in a vm

Since the urls always work correctly when I am in the browser, I can be sure that there is no typo or that something is absolutely incorrect there.

The error message looks like there is an error in my manifest, but I cant figure it out alone. Maybe I am just blind by watching on it the whole day. Am I missing an important part in the manifest? Are the tenant settings which has to be made that this is working in the desktop app?

Best regards and hopefully someone can help me here. Thanks in advance

**Comment by YannickRe** [comment]
I have some other things you can try:
- Switch the order of the `webApplicationInfo`. It shouldn't make a difference, but you may never know. First put `id` and then put `resource`.
- Valid your manifest in App Studio (or create your manifest). It'll for sure create a valid manifest. App Studio is an app you can install from the Teams app store into your Teams client.
- Have you tried installing my app? Just to see if that works :)

**Comment by diabhoil** [comment]
So first of. I tried to install your app and it is working.

I switched the order, copied the block from your manifest after gulping it. Valid the app in App Studio (i created it there in the first place). Everything is fine. Just 2 warnings regarding the terms & conditions link and having a wildcard in the valid domain section. But that is the same in your manifest (plus the AppSource Validation Process will mark this as error anyway. So having a *.sharepoint.com domain in this section wont get your app in the official stores)

But since your app is working, it all looks like an error in the JavaScript part. I'll check that...

**Comment by diabhoil** [comment]
Looks like I found the solution. Everytime I upload a new version from the app, just the personal app will be updated, but not the version of the app deployed to a team.
I have to manually remove the app from the team (with all tabs belonging to the app) and then deploy the new version to the team to get the newest version.

**Comment by YannickRe** [comment]
This seems normal behavior if you are side loading the app, as there is no "central" installation. If you deploy through Teams Admin Center or upload in your Teams App Store (and increase the version number), this should be reflected in each team where the app is installed.

**Comment by diabhoil** [comment]
Mhh yes it might be normal behavior. But not thaaat obvious when side loading only. 

But thanks anyway. Your app and article helped me to find a working way to link sharepoint pages. And I found a new source of errors xD
